apiVersion: v1
kind: Service
metadata:
  name: employee-backend
  namespace: employee-system
spec:
  selector:
    app: employee-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP