apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  namespace: employee-system
  labels:
    app: employee-service
    version: "2.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
        version: "2.0.0"
    spec:
      containers:
        - name: employee-service
          image: employee-service:v2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10