apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: employee-system
  labels:
    app: employee-service
    version: "2.0.0"
spec:
  selector:
    app: employee-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP